PUT http://localhost:3000/api/event/611083655591763d4c19c8ad
Content-Type: application/json

{
   "title": "Testeo de Actualizacion2",
   "description":"Es para observar la actualizacion",
    "place":{
      "codlocalidad": 2,
      "nombrelocalidad": "Catamarca",
      "Direccion": "plaza 25 Mayo"
    },
   "important": true
}

###
PUT http://localhost:3000/api/event/1
Content-Type: application/json

{
   "title": "Torneo internacional de Ajedrez",
   "description":"Torneo entre las grandes promesas de este juego",
    "place":{
      "codlocalidad": 2,
      "nombrelocalidad": "Catamarca",
      "Direccion": "plaza 25 Mayo"
    },
   "important": true,
   "urlimage":"http://unsitioconimagenes/id"
}
